MESSAGE-INTEGRITY encoding and decoding
esl/jerboa pull request #64
Opened 2017-03-16 08:15 UTC by arkgil

Addresses #56 .

Providing options to `Format.encode/2` and `Format.decode/2` users can apply and verify MESSAGE-INTEGRITY in STUN messages.

2017-03-16 08:18 UTC, arkgil commented
Well, it looks like Credo doesn't know how binary pattern-matching works.

2017-03-20 11:14 UTC, mentels requested changes

2017-03-20 11:14 UTC, mentels commented on lib/jerboa/format.ex
> +  If any of these values is missing, message integrity won't be applied
I don't understand this paragraph :)

2017-03-20 11:14 UTC, mentels commented on lib/jerboa/format.ex
> +    if USERNAME attribute can't be found in params struct
`in the params struct`

2017-03-20 11:14 UTC, mentels commented on lib/jerboa/format.ex
> +    if USERNAME attribute can't be found in params struct
But hey, what this sentence is about, after all?

2017-03-20 11:14 UTC, mentels commented on lib/jerboa/format.ex
> +    if USERNAME attribute can't be found in params struct
Ahh I see: if it's not in the params from the message then the options will be used

2017-03-20 11:14 UTC, mentels commented on lib/jerboa/format.ex
> +  in decoded message attributes or in the options list if there are
`in the decoded messagez

2017-03-20 11:14 UTC, mentels commented on lib/jerboa/format.ex
> +  If any of these values is missing, message integrity won't be applied
"If any of these values **are** missing"

2017-03-20 11:14 UTC, mentels commented on lib/jerboa/format/body.ex
> +      meta.length_up_to_integrity + 4 + l + padding_length
This is not readable. The reader needs to guess that 4 is for the attribute type and the length. Actually, getting the *rest* could be abstracted out to a separate function - `decode/2` doesn't have to deal with paddings.  And the `meta` could also be updated in a more readable way, I belive.

2017-03-20 11:14 UTC, mentels commented on lib/jerboa/format/message_integrity.ex
> +    case meta.message_integrity do
That could be simplified to `byte_size(meta.message_integrity) > 0

2017-03-20 11:14 UTC, mentels commented on test/jerboa/format/message_integrity_test.exs
> +      assert meta == MessageIntegrity.apply(meta)
I don't know why this assertion works (I can only guess)

2017-03-20 11:14 UTC, mentels commented on test/jerboa/format/message_integrity_test.exs
> +      assert byte_size(meta.body) + 24 == byte_size(new_meta.body)
24?

2017-03-20 11:14 UTC, mentels commented on test/jerboa/format/message_integrity_test.exs
> +      assert {:ok, meta} == MessageIntegrity.verify(meta)
I don't know what this assertion checks.

2017-03-20 11:14 UTC, mentels commented on test/jerboa/format_test.exs
> +    assert {:ok, _} = Format.decode(bin, secret: secret)
The symmetry is not clearly visible.

2017-03-23 08:09 UTC, arkgil commented
@mentels I addressed the issues you pointed out.

2017-03-27 10:30 UTC, mentels approved these changes

2017-03-27 10:30 UTC, mentels commented on test/jerboa/format/message_integrity_test.exs
> +      assert meta.body == body_without_mi
Now I know exactly what the test is about.

2017-03-27 10:30 UTC, merged